/**
 * Generates embedded migrations for production builds
 * This reads all migration SQL files and creates a TypeScript file
 * that can be bundled into the compiled binary
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const MIGRATIONS_DIR = join(__dirname, '../drizzle/migrations')
const OUTPUT_FILE = join(__dirname, '../src/db/migrations/embedded.ts')

interface JournalEntry {
  idx: number
  version: string
  when: number
  tag: string
  breakpoints: boolean
}

interface Journal {
  version: string
  dialect: string
  entries: JournalEntry[]
}

function main() {
  // Read the journal
  const journalPath = join(MIGRATIONS_DIR, 'meta/_journal.json')
  const journal: Journal = JSON.parse(readFileSync(journalPath, 'utf-8'))

  // Read all SQL migration files
  const migrations: { tag: string; sql: string; when: number }[] = []

  for (const entry of journal.entries) {
    const sqlPath = join(MIGRATIONS_DIR, `${entry.tag}.sql`)
    const sql = readFileSync(sqlPath, 'utf-8')
    migrations.push({
      tag: entry.tag,
      sql,
      when: entry.when,
    })
  }

  // Generate TypeScript file
  const output = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-embedded-migrations.ts
 *
 * Contains all Drizzle migrations embedded as strings for production builds
 */

export interface EmbeddedMigration {
  tag: string
  sql: string
  when: number
}

export const EMBEDDED_JOURNAL = ${JSON.stringify(journal, null, 2)} as const

export const EMBEDDED_MIGRATIONS: EmbeddedMigration[] = ${JSON.stringify(migrations, null, 2)}
`

  writeFileSync(OUTPUT_FILE, output)
}

main()
