/**
 * Generates embedded migrations for production builds
 * This reads all migration SQL files and creates a TypeScript file
 * that can be bundled into the compiled binary
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const MIGRATIONS_DIR = join(__dirname, '../drizzle/migrations')
const OUTPUT_FILE = join(__dirname, '../src/db/migrations/embedded.ts')

interface JournalEntry {
  idx: number
  version: string
  when: number
  tag: string
  breakpoints: boolean
}

interface Journal {
  version: string
  dialect: string
  entries: JournalEntry[]
}

function main() {
  // Read the journal
  const journalPath = join(MIGRATIONS_DIR, 'meta/_journal.json')
  const journal: Journal = JSON.parse(readFileSync(journalPath, 'utf-8'))

  // Read all SQL migration files
  const migrations: { tag: string; sql: string; when: number }[] = []

  for (const entry of journal.entries) {
    const sqlPath = join(MIGRATIONS_DIR, `${entry.tag}.sql`)
    const sql = readFileSync(sqlPath, 'utf-8')
    migrations.push({
      tag: entry.tag,
      sql,
      when: entry.when,
    })
  }

  // Helper to format object with proper Biome style
  function formatObject(obj: unknown, indent = 0): string {
    const spaces = ' '.repeat(indent)
    const nextSpaces = ' '.repeat(indent + 2)

    if (obj === null) return 'null'
    if (typeof obj === 'string') {
      let escaped: string
      // Use double quotes for single-line strings with single quotes (SQL DEFAULT clauses)
      // Use single quotes for multiline strings (to avoid double-escaping)
      if (obj.includes("'") && !obj.includes('\n') && !obj.includes('\r')) {
        escaped = obj.replace(/\\/g, '\\\\').replace(/"/g, '\\"')
        return `"${escaped}"`
      }
      // Default to single quotes for all other strings
      escaped = obj
        .replace(/\\/g, '\\\\')
        .replace(/'/g, "\\'")
        .replace(/\n/g, '\\n')
        .replace(/\r/g, '\\r')
        .replace(/\t/g, '\\t')
      return `'${escaped}'`
    }
    if (typeof obj === 'number' || typeof obj === 'boolean') return String(obj)

    if (Array.isArray(obj)) {
      if (obj.length === 0) return '[]'
      const items = obj.map(
        (item) => `${nextSpaces}${formatObject(item, indent + 2)}`,
      )
      return `[\n${items.join(',\n')},\n${spaces}]`
    }

    if (typeof obj === 'object') {
      const keys = Object.keys(obj)
      if (keys.length === 0) return '{}'
      const items = keys.map((key) => {
        const value = (obj as Record<string, unknown>)[key]
        return `${nextSpaces}${key}: ${formatObject(value, indent + 2)}`
      })
      return `{\n${items.join(',\n')},\n${spaces}}`
    }

    return String(obj)
  }

  const journalStr = formatObject(journal)
  const migrationsStr = formatObject(migrations)

  const output = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-embedded-migrations.ts
 *
 * Contains all Drizzle migrations embedded as strings for production builds
 */

export interface EmbeddedMigration {
  tag: string
  sql: string
  when: number
}

export const EMBEDDED_JOURNAL = ${journalStr} as const

export const EMBEDDED_MIGRATIONS: EmbeddedMigration[] = ${migrationsStr}
`

  writeFileSync(OUTPUT_FILE, output)
}

main()
