/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SongsIndexRouteImport } from './routes/songs/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SchedulesIndexRouteImport } from './routes/schedules/index'
import { Route as PresentIndexRouteImport } from './routes/present/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as rootIndexRouteImport } from './routes/(root)/index'
import { Route as SongsSongIdRouteImport } from './routes/songs/$songId'
import { Route as SchedulesScheduleIdRouteImport } from './routes/schedules/$scheduleId'
import { Route as DisplayDisplayIdRouteImport } from './routes/display/$displayId'

const SongsIndexRoute = SongsIndexRouteImport.update({
  id: '/songs/',
  path: '/songs/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesIndexRoute = SchedulesIndexRouteImport.update({
  id: '/schedules/',
  path: '/schedules/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentIndexRoute = PresentIndexRouteImport.update({
  id: '/present/',
  path: '/present/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const rootIndexRoute = rootIndexRouteImport.update({
  id: '/(root)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsSongIdRoute = SongsSongIdRouteImport.update({
  id: '/songs/$songId',
  path: '/songs/$songId',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesScheduleIdRoute = SchedulesScheduleIdRouteImport.update({
  id: '/schedules/$scheduleId',
  path: '/schedules/$scheduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayDisplayIdRoute = DisplayDisplayIdRouteImport.update({
  id: '/display/$displayId',
  path: '/display/$displayId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/display/$displayId': typeof DisplayDisplayIdRoute
  '/schedules/$scheduleId': typeof SchedulesScheduleIdRoute
  '/songs/$songId': typeof SongsSongIdRoute
  '/': typeof rootIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/present': typeof PresentIndexRoute
  '/schedules': typeof SchedulesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/songs': typeof SongsIndexRoute
}
export interface FileRoutesByTo {
  '/display/$displayId': typeof DisplayDisplayIdRoute
  '/schedules/$scheduleId': typeof SchedulesScheduleIdRoute
  '/songs/$songId': typeof SongsSongIdRoute
  '/': typeof rootIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/present': typeof PresentIndexRoute
  '/schedules': typeof SchedulesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/songs': typeof SongsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/display/$displayId': typeof DisplayDisplayIdRoute
  '/schedules/$scheduleId': typeof SchedulesScheduleIdRoute
  '/songs/$songId': typeof SongsSongIdRoute
  '/(root)/': typeof rootIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/present/': typeof PresentIndexRoute
  '/schedules/': typeof SchedulesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/songs/': typeof SongsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/display/$displayId'
    | '/schedules/$scheduleId'
    | '/songs/$songId'
    | '/'
    | '/dashboard'
    | '/present'
    | '/schedules'
    | '/settings'
    | '/songs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/display/$displayId'
    | '/schedules/$scheduleId'
    | '/songs/$songId'
    | '/'
    | '/dashboard'
    | '/present'
    | '/schedules'
    | '/settings'
    | '/songs'
  id:
    | '__root__'
    | '/display/$displayId'
    | '/schedules/$scheduleId'
    | '/songs/$songId'
    | '/(root)/'
    | '/dashboard/'
    | '/present/'
    | '/schedules/'
    | '/settings/'
    | '/songs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DisplayDisplayIdRoute: typeof DisplayDisplayIdRoute
  SchedulesScheduleIdRoute: typeof SchedulesScheduleIdRoute
  SongsSongIdRoute: typeof SongsSongIdRoute
  rootIndexRoute: typeof rootIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  PresentIndexRoute: typeof PresentIndexRoute
  SchedulesIndexRoute: typeof SchedulesIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SongsIndexRoute: typeof SongsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/songs/': {
      id: '/songs/'
      path: '/songs'
      fullPath: '/songs'
      preLoaderRoute: typeof SongsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules/': {
      id: '/schedules/'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof SchedulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/present/': {
      id: '/present/'
      path: '/present'
      fullPath: '/present'
      preLoaderRoute: typeof PresentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(root)/': {
      id: '/(root)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof rootIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/$songId': {
      id: '/songs/$songId'
      path: '/songs/$songId'
      fullPath: '/songs/$songId'
      preLoaderRoute: typeof SongsSongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules/$scheduleId': {
      id: '/schedules/$scheduleId'
      path: '/schedules/$scheduleId'
      fullPath: '/schedules/$scheduleId'
      preLoaderRoute: typeof SchedulesScheduleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display/$displayId': {
      id: '/display/$displayId'
      path: '/display/$displayId'
      fullPath: '/display/$displayId'
      preLoaderRoute: typeof DisplayDisplayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DisplayDisplayIdRoute: DisplayDisplayIdRoute,
  SchedulesScheduleIdRoute: SchedulesScheduleIdRoute,
  SongsSongIdRoute: SongsSongIdRoute,
  rootIndexRoute: rootIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  PresentIndexRoute: PresentIndexRoute,
  SchedulesIndexRoute: SchedulesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SongsIndexRoute: SongsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
