// Generated by Wrangler by running `wrangler types`

interface Env {
	YOUTUBE_SCOPE: "https://www.googleapis.com/auth/youtube.force-ssl";
	COOKIE_NAME: "yt_oauth_state";
	COOKIE_MAX_AGE: 600;
	YOUTUBE_CLIENT_ID: string;
	YOUTUBE_CLIENT_SECRET: string;
	YOUTUBE_REDIRECT_URI: string;
	COOKIE_ENCRYPTION_KEY: string;
	ALLOWED_ORIGINS: string;
}
