export const TITLE_MAX_LENGTH = 120
export const NOTES_MAX_LENGTH = 5000
export const SHORT_FIELD_MAX_LENGTH = 500
export const SELECTOR_MAX_LENGTH = 2000
export const SCREENSHOT_MAX_BYTES = 5 * 1024 * 1024
export const GITHUB_REPO = 'radio-crestin/church-hub'
export const GITHUB_ISSUE_LABEL = 'feature-request'
export const SCREENSHOT_ROUTE_PREFIX = '/feature-requests/screenshots'
export const DEFAULT_WAHA_SESSION = 'default'
