#!/usr/bin/env bun
/**
 * Release-notes generator.
 *
 * Parses the git history (Conventional Commits) between version tags and
 * produces the changelog in two forms:
 *
 *   1. CHANGELOG.md  (repo root)              — human-readable, version-controlled.
 *   2. changelog.json (client feature data)   — structured, bundled into the app
 *      so the "Release Notes" section in Settings > About works offline.
 *
 * Both are regenerated by scripts/release.sh on every version bump (before the
 * tag is cut), so the build that ships for version X already contains X's notes.
 *
 * Usage:
 *   bun app/scripts/generate-changelog.ts            # regenerate both files
 *   bun app/scripts/generate-changelog.ts --check    # fail if files are stale
 *
 * Commits are grouped into exactly three buckets to match the UI:
 *   feat        -> Features
 *   fix         -> Bug Fixes
 *   everything  -> Changes   (refactor, perf, chore, docs, build, style, revert…)
 *   (excluded: merge commits, version-bump commits, ci/test noise)
 */

import { execSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'

const REPO_ROOT = join(import.meta.dir, '..', '..')
const CONF_FILE = join(REPO_ROOT, 'app', 'tauri', 'tauri.conf.json')
const CHANGELOG_MD = join(REPO_ROOT, 'CHANGELOG.md')
const CHANGELOG_JSON = join(
  REPO_ROOT,
  'app',
  'apps',
  'client',
  'src',
  'features',
  'release-notes',
  'changelog.generated.json',
)

// Conventional-commit types that are pure internal noise — never surfaced.
const EXCLUDED_TYPES = new Set(['ci', 'test'])

/** Chore subjects that are the release itself rather than part of it. */
const RELEASE_PLUMBING = /^(?:bump|sync|regenerate|update) (?:version|changelog)\b/i

interface ChangeEntry {
  scope: string | null
  message: string
}

interface VersionNotes {
  version: string
  date: string | null
  features: ChangeEntry[]
  bugFixes: ChangeEntry[]
  changes: ChangeEntry[]
}

function git(args: string): string {
  return execSync(`git ${args}`, {
    cwd: REPO_ROOT,
    encoding: 'utf-8',
    maxBuffer: 64 * 1024 * 1024,
  }).trim()
}

function readCurrentVersion(): string {
  const raw = readFileSync(CONF_FILE, 'utf-8')
  const match = raw.match(/"version"\s*:\s*"([^"]+)"/)
  if (!match?.[1]) {
    throw new Error(`Could not read version from ${CONF_FILE}`)
  }
  return match[1]
}

/** All version tags, newest first (semver-aware). */
function listTags(): string[] {
  const out = git("tag --list 'v[0-9]*' --sort=-version:refname")
  return out ? out.split('\n').filter(Boolean) : []
}

function tagDate(ref: string): string | null {
  try {
    return git(`log -1 --pretty=%cI ${ref}`)
  } catch {
    return null
  }
}

/** Parse a single commit subject line into a categorized entry. */
function parseSubject(
  subject: string,
): { bucket: keyof Pick<VersionNotes, 'features' | 'bugFixes' | 'changes'>; entry: ChangeEntry } | null {
  const match = subject.match(/^(\w+)(?:\(([^)]+)\))?(!)?:\s*(.+)$/)

  const type = match?.[1]?.toLowerCase() ?? null
  const scope = match?.[2] ?? null
  // Strip a trailing PR reference like " (#29)" for a cleaner UI.
  const message = (match?.[4] ?? subject).replace(/\s*\(#\d+\)\s*$/, '').trim()

  if (!message) return null

  // Drop release plumbing and internal-only types. Bumping the version,
  // syncing it back from CI and regenerating this file are how a release is
  // cut — they are not something that happens *in* the release, and listing
  // them tells a reader nothing about what changed in the app.
  if (type === 'chore' && RELEASE_PLUMBING.test(message)) return null
  if (type && EXCLUDED_TYPES.has(type)) return null

  if (type === 'feat') return { bucket: 'features', entry: { scope, message } }
  if (type === 'fix') return { bucket: 'bugFixes', entry: { scope, message } }
  return { bucket: 'changes', entry: { scope, message } }
}

/** Collect categorized commits in a `from..to` range (exclusive of `from`). */
function notesForRange(range: string): Pick<VersionNotes, 'features' | 'bugFixes' | 'changes'> {
  const buckets = { features: [], bugFixes: [], changes: [] } as Pick<
    VersionNotes,
    'features' | 'bugFixes' | 'changes'
  >

  const log = git(`log --no-merges --pretty=format:%s ${range}`)
  if (!log) return buckets

  for (const subject of log.split('\n')) {
    const parsed = parseSubject(subject)
    if (parsed) buckets[parsed.bucket].push(parsed.entry)
  }
  return buckets
}

function buildVersionList(): VersionNotes[] {
  const tags = listTags()
  const currentVersion = readCurrentVersion()
  const versions: VersionNotes[] = []

  // Unreleased: the version in tauri.conf.json has no tag yet (release.sh runs
  // this after bumping the version but before tagging). Capture commits since
  // the latest tag so the shipping build includes its own notes.
  if (tags.length > 0 && !tags.includes(`v${currentVersion}`)) {
    const buckets = notesForRange(`${tags[0]}..HEAD`)
    const total =
      buckets.features.length + buckets.bugFixes.length + buckets.changes.length
    if (total > 0) {
      versions.push({ version: currentVersion, date: tagDate('HEAD'), ...buckets })
    }
  }

  for (let i = 0; i < tags.length; i++) {
    const tag = tags[i]
    const prev = tags[i + 1]
    const range = prev ? `${prev}..${tag}` : tag
    versions.push({
      version: tag.replace(/^v/, ''),
      date: tagDate(tag),
      ...notesForRange(range),
    })
  }

  return versions
}

function renderEntry(entry: ChangeEntry): string {
  return entry.scope
    ? `- **${entry.scope}**: ${entry.message}`
    : `- ${entry.message}`
}

function renderMarkdown(versions: VersionNotes[]): string {
  const lines: string[] = [
    '# Changelog',
    '',
    '> Auto-generated from git history by `app/scripts/generate-changelog.ts`. Do not edit by hand.',
    '',
  ]

  for (const v of versions) {
    const date = v.date ? v.date.slice(0, 10) : ''
    lines.push(`## v${v.version}${date ? ` — ${date}` : ''}`, '')

    const sections: Array<[string, ChangeEntry[]]> = [
      ['### 🚀 Features', v.features],
      ['### 🐛 Bug Fixes', v.bugFixes],
      ['### 🔧 Changes', v.changes],
    ]

    let hadContent = false
    for (const [heading, entries] of sections) {
      if (entries.length === 0) continue
      hadContent = true
      lines.push(heading, '')
      for (const entry of entries) lines.push(renderEntry(entry))
      lines.push('')
    }

    if (!hadContent) lines.push('_No notable changes._', '')
  }

  return `${lines.join('\n').trimEnd()}\n`
}

function main(): void {
  const check = process.argv.includes('--check')
  const versions = buildVersionList()

  const markdown = renderMarkdown(versions)
  const json = `${JSON.stringify(versions, null, 2)}\n`

  if (check) {
    const mdStale = !existsSync(CHANGELOG_MD) || readFileSync(CHANGELOG_MD, 'utf-8') !== markdown
    const jsonStale =
      !existsSync(CHANGELOG_JSON) || readFileSync(CHANGELOG_JSON, 'utf-8') !== json
    if (mdStale || jsonStale) {
      console.error('Changelog is stale. Run: bun app/scripts/generate-changelog.ts')
      process.exit(1)
    }
    console.log('Changelog is up to date.')
    return
  }

  mkdirSync(dirname(CHANGELOG_JSON), { recursive: true })
  writeFileSync(CHANGELOG_MD, markdown)
  writeFileSync(CHANGELOG_JSON, json)

  console.log(
    `Generated changelog for ${versions.length} versions:\n  ${CHANGELOG_MD}\n  ${CHANGELOG_JSON}`,
  )
}

main()
